Genericarticle:
    type: entity
    table: GenericArticle
    indexes:
        fk_GenericArticle_Category1_idx:
            columns:
                - Category_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            fixed: false
            comment: ''
        description:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        isactive:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: isActive
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
