PaymentMethod:
    type: entity
    table: payment_method
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            fixed: false
    lifecycleCallbacks: {  }
