User:
    type: entity
    table: User
    indexes:
        fk_User_seller_infos1_idx:
            columns:
                - seller_infos_id
    uniqueConstraints:
        UNIQ_2DA1797792FC23A8:
            columns:
                - username_canonical
        UNIQ_2DA17977A0D96FBF:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
        usernameCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: username_canonical
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        emailCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
            nullable: false
        expired:
            type: boolean
            nullable: false
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            fixed: false
        credentialsExpired:
            type: boolean
            nullable: false
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
    manyToOne:
        sellerInfos:
            targetEntity: SellerInfos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                seller_infos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
