odysseus_admin_home_routes:
    resource: "@OdysseusFrontBundle/Controller/HomeController.php"
    type:     annotation

odysseus_admin_user_routes:
    resource: "@OdysseusFrontBundle/Controller/UserController.php"
    type:     annotation

odysseus_admin_article_routes:
    resource: "@OdysseusFrontBundle/Controller/ArticleController.php"
    type:     annotation

odysseus_admin_order_routes:
    resource: "@OdysseusFrontBundle/Controller/OrderController.php"
    type:     annotation
    
odysseus_admin_category_routes:
    resource: "@OdysseusFrontBundle/Controller/CategoryController.php"
    type:     annotation

