<?php

namespace Odysseus\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderArticleRepository extends EntityRepository
{
}
