<?php

namespace Odysseus\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailsRepository extends EntityRepository
{
}
